config/routes.rb
Rails.application.routes.draw do
  #get 'tasks/index'
  resources :tasks, only: :index do
  	resources :assigments, only: [:create, :update]
  end
  root to: 'assigments#index'
  get 'assigments/tasks_list'
  get 'assigments/task_one'
  get 'assigments/task_two'
  get 'assigments/task_three'
  get 'assigments/task_four'
  get 'assigments/task_five'
  get 'assigments/task_six'
  get 'assigments/task_seven'
  get 'assigments/task_eigth'
  get 'assigments/task_nine'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users,  controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'

  }


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assigment.rb
class Assigment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
	has_many :assigments
	has_many :users, through: :assigments
end

app/models/user.rb
class User < ApplicationRecord
  after_create :add_task
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :assigments         
  has_many :tasks, through: :assigments

  def add_task

	Task.all.each do |t|
	   self.assigments.build(task: t)
	   self.save 
	end

  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assigments_controller.rb
class AssigmentsController < ApplicationController
	before_action :authenticate_user!
	
	def create
		@task = Task.find(params[:task_id])
		@assigment = Assigment.new(task: @task, user: current_user, complete: true )
		if @assigment.save
			redirect_to tasks_path, notice:'La tarea fue completada'
		else
			redirect_to tasks_path, alert: 'La tarea no fue ingresada'
		end
	end

	def index
		@assigments = current_user.assigments
	

		
	end

	def tasks_list
		@assigments = Assigment.all
		@users = User.all
		@tasks = Task.all
	end

	def task_one
		@assigments = Assigment.all
		@users = User.all
		@tasks = Task.all
	end
	def task_two
		@assigments = Assigment.all
		@users = User.all
		@tasks = Task.all
	end
	def task_three
		@assigments = Assigment.all
		@users = User.all
		@tasks = Task.all
	end
	def task_four
		@assigments = Assigment.all
		@users = User.all
		@tasks = Task.all
	end
	def task_five
		@assigments = Assigment.all
		@users = User.all
		@tasks = Task.all
	end
	def task_six
		@assigments = Assigment.all
		@users = User.all
		@tasks = Task.all
	end
	def task_seven
		@assigments = Assigment.all
		@users = User.all
		@tasks = Task.all
	end
	def task_eigth
		@assigments = Assigment.all
		@users = User.all
		@tasks = Task.all
	end
	def task_nine
		@assigments = Assigment.all
		@users = User.all
		@tasks = Task.all
	end
	def update
		
		if current_user.assigments.find(params[:id]).complete == false
			current_user.assigments.find(params[:id]).update(complete:true)
			redirect_to root_path
		else 
			current_user.assigments.find(params[:id]).update(complete:false)
			redirect_to root_path
		end
				
	end



end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
  	@tasks = Task.all
  	
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
   devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
   before_action :configure_sign_in_params, only: [:create, :destroy]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
     super
  end

  # DELETE /resource/sign_out
   def destroy
     super
   end


  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
   devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assigments_helper.rb
module AssigmentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/assigments/index.html.erb
<div class="container">
	<div class="row">
		<% @assigments.each do |a| %>
			<div class="col">
				<div class="card" >
					<%= image_tag a.task.photo , :size => "200x200", class: 'card-img-top img-thumbnail' %>
					<div class="body">		
					    <h1><%= a.task.name  %></h1>

						<p><%= a.task.description  %></p>
						<% if  a.complete == false %>
							<%= link_to "No realizada", task_assigment_path(a.task.id, a.id), class: "btn btn-danger", method: :patch %>
							<% if a.task.id == 1 %>
								<%= link_to "¿quién la ha completado?", assigments_task_one_path, class:"btn btn-info"%> 
							<% elsif a.task.id == 2 %>
								<%= link_to "¿quién la ha completado?", assigments_task_two_path, class:"btn btn-info"%>
							<% elsif a.task.id == 3 %>
								<%= link_to "¿quién la ha completado?", assigments_task_three_path, class:"btn btn-info"%>
							<% elsif a.task.id == 4 %>
								<%= link_to "¿quién la ha completado?", assigments_task_four_path, class:"btn btn-info"%>
							<% elsif a.task.id == 5 %>
								<%= link_to "¿quién la ha completado?", assigments_task_five_path, class:"btn btn-info"%>
							<% elsif a.task.id == 6 %>
								<%= link_to "¿quién la ha completado?", assigments_task_six_path, class:"btn btn-info"%>
							<% elsif a.task.id == 7 %>
								<%= link_to "¿quién la ha completado?", assigments_task_seven_path, class:"btn btn-info"%>
							<% elsif a.task.id == 8 %>
								<%= link_to "¿quién la ha completado?", assigments_task_eigth_path, class:"btn btn-info"%>
							<% elsif a.task.id == 9 %>
								<%= link_to "¿quién la ha completado?", assigments_task_nine_path, class:"btn btn-info"%>
							<%end%>
						<% else %>
								
							<%= link_to "Listo", task_assigment_path(a.task.id, a.id), class: "btn btn-success", method: :patch %>
							<% if a.task.id == 1 %>
								<%= link_to "¿quién la ha completado?", assigments_task_one_path, class:"btn btn-info"%> 
							<% elsif a.task.id == 2 %>
								<%= link_to "¿quién la ha completado?", assigments_task_two_path, class:"btn btn-info"%>
							<% elsif a.task.id == 3 %>
								<%= link_to "¿quién la ha completado?", assigments_task_three_path, class:"btn btn-info"%>
							<% elsif a.task.id == 4 %>
								<%= link_to "¿quién la ha completado?", assigments_task_four_path, class:"btn btn-info"%>
							<% elsif a.task.id == 5 %>
								<%= link_to "¿quién la ha completado?", assigments_task_five_path, class:"btn btn-info"%>
							<% elsif a.task.id == 6 %>
								<%= link_to "¿quién la ha completado?", assigments_task_six_path, class:"btn btn-info"%>
							<% elsif a.task.id == 7 %>
								<%= link_to "¿quién la ha completado?", assigments_task_seven_path, class:"btn btn-info"%>
							<% elsif a.task.id == 8 %>
								<%= link_to "¿quién la ha completado?", assigments_task_eigth_path, class:"btn btn-info"%>
							<% elsif a.task.id == 9 %>
								<%= link_to "¿quién la ha completado?", assigments_task_nine_path, class:"btn btn-info"%>
							<%end%>
						<% end %>
					</div>
				</div>
			</div>

			
			<div class="w-100" style="margin:20px" ></div>
		<% end %>
	</div>
</div>

app/views/assigments/task_eigth.html.erb
<br>
<h1> <%= @assigments.find_by(:task_id=>"8").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"8", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"8", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"8", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	<%end%>
<%end%>
<br>


<br>
<h1> <%= @assigments.find_by(:task_id=>"8").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"8", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"8", :user_id=>u.id).user.name %></li> 
	<%end%>
<%end%>
<br>

app/views/assigments/task_five.html.erb
<br>
<h1> <%= @assigments.find_by(:task_id=>"5").task.name %></h1>
<% @users.each do |u| %>
	<%if @assigments.find_by(:task_id=>"5", :user_id=>u.id).complete == true%>
		 <li><%= @assigments.find_by(:task_id=>"5", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"5", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	
	<%end%>
<%end%>
<br>
<h1> <%= @assigments.find_by(:task_id=>"5").task.name %></h1>
<% @users.each do |u| %>
	<%if @assigments.find_by(:task_id=>"5", :user_id=>u.id).complete == true%>
		 <li><%= @assigments.find_by(:task_id=>"5", :user_id=>u.id).user.name %></li> 
	<%end%>
<%end%>
<br>

app/views/assigments/task_four.html.erb
<br>
<h1> <%= @assigments.find_by(:task_id=>"4").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"4", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"4", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"4", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	
	<%end%>
<%end%>
<br>
<h1> <%= @assigments.find_by(:task_id=>"4").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"4", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"4", :user_id=>u.id).user.name %></li> 
	<%end%>
<%end%>
<br>

app/views/assigments/task_nine.html.erb
<br>
<h1> <%= @assigments.find_by(:task_id=>"9").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"9", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"9", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"9", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	
	<%end%>
<%end%>
<br>
<h1> <%= @assigments.find_by(:task_id=>"9").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"9", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"9", :user_id=>u.id).user.name %></li> 	
	<%end%>
<%end%>

app/views/assigments/task_one.html.erb
<br>
<h1> <%= @assigments.find_by(:task_id=>"1").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"1", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"1", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"1", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	<%end%>
<%end%>
<br>

<br>
<h1> <%= @assigments.find_by(:task_id=>"1").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"1", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"1", :user_id=>u.id).user.name %></li> 
	<%end%>
<%end%>
<br>

app/views/assigments/task_seven.html.erb
<br>
<h1> <%= @assigments.find_by(:task_id=>"7").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"7", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"7", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"7", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	
	<%end%>
<%end%>
<br>
<h1> <%= @assigments.find_by(:task_id=>"7").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"7", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"7", :user_id=>u.id).user.name %></li> 
	<%end%>
<%end%>
<br>

app/views/assigments/task_six.html.erb
<br>
<h1> <%= @assigments.find_by(:task_id=>"6").task.name %></h1>
<% @users.each do |u| %>
	<%if @assigments.find_by(:task_id=>"6", :user_id=>u.id).complete == true%>
		 <li><%= @assigments.find_by(:task_id=>"6", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"6", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	
	<%end%>
<%end%>
<br>
<h1> <%= @assigments.find_by(:task_id=>"6").task.name %></h1>
<% @users.each do |u| %>
	<%if @assigments.find_by(:task_id=>"6", :user_id=>u.id).complete == true%>
		 <li><%= @assigments.find_by(:task_id=>"6", :user_id=>u.id).user.name %></li> 
	<%end%>
<%end%>

app/views/assigments/task_three.html.erb
<br>
<h1> <%= @assigments.find_by(:task_id=>"3").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"3", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"3", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"3", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	
	<%end%>
<%end%>
<br>
<h1> <%= @assigments.find_by(:task_id=>"3").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"3", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"3", :user_id=>u.id).user.name %></li> 
	<%end%>
<%end%>
<br>

app/views/assigments/task_two.html.erb
<br>
<h1> <%= @assigments.find_by(:task_id=>"2").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"2", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"2", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"2", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	<% end %>
<%end%>
<br>
<h1> <%= @assigments.find_by(:task_id=>"2").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"2", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"2", :user_id=>u.id).user.name %></li> 
	<% end %>
<%end%>

app/views/assigments/tasks_list.html.erb
<br>
<h1> <%= @assigments.find_by(:task_id=>"1").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"1", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"1", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"1", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	<%end%>
<%end%>
<br>
<h1> <%= @assigments.find_by(:task_id=>"2").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"2", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"2", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"2", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	<% end %>
<%end%>
<br>
<h1> <%= @assigments.find_by(:task_id=>"3").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"3", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"3", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"3", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	
	<%end%>
<%end%>
<br>
<h1> <%= @assigments.find_by(:task_id=>"4").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"4", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"4", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"4", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	
	<%end%>
<%end%>
<br>
<h1> <%= @assigments.find_by(:task_id=>"5").task.name %></h1>
<% @users.each do |u| %>
	<%if @assigments.find_by(:task_id=>"5", :user_id=>u.id).complete == true%>
		 <li><%= @assigments.find_by(:task_id=>"5", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"5", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	
	<%end%>
<%end%>
<br>
<h1> <%= @assigments.find_by(:task_id=>"6").task.name %></h1>
<% @users.each do |u| %>
	<%if @assigments.find_by(:task_id=>"6", :user_id=>u.id).complete == true%>
		 <li><%= @assigments.find_by(:task_id=>"6", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"6", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	
	<%end%>
<%end%>
<br>
<h1> <%= @assigments.find_by(:task_id=>"7").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"7", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"7", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"7", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	
	<%end%>
<%end%>
<br>
<h1> <%= @assigments.find_by(:task_id=>"8").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"8", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"8", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"8", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	
	<%end%>
<%end%>
<br>
<h1> <%= @assigments.find_by(:task_id=>"9").task.name %></h1>
<% @users.each do |u| %>
	<% if @assigments.find_by(:task_id=>"9", :user_id=>u.id).complete == true %>
		 <li><%= @assigments.find_by(:task_id=>"9", :user_id=>u.id).user.name %></li> 
		 <li><%= image_tag @assigments.find_by(:task_id=>"9", :user_id=>u.id).user.avatar  , :size => "100x100" %></li>
	
	<%end%>
<%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href=""><%= image_tag current_user.avatar,  :size => "40x40", class: 'card-img-top img-thumbnail' %></a></li>
          <li><a href="#" ><%= current_user.name %><span class="sr-only"></span></a></li>
          <li><a href="<%= destroy_user_session_path %>" data-method="DELETE">LOG OUT<span class="sr-only">(current)</span></a></li>
          <li><a href="<%= root_path%>"> TAREAS</a></li>
          <li><a href="<%= assigments_tasks_list_path%>">  RANKING DE TAREAS</a></li>
          

          <li><a href="#"> CANTIDAD DE TAREAS COMPLETADAS = (
              <%= current_user.assigments.group(:complete).count.map{|k,v| v}[1]%> )</a>
            <ul class="dropdown-menu">
              <li><a href="#"><% link_to "Log out", destroy_user_session_path %></a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        
      </div><!-- /.navbar-collapse -->
    <% else %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">  
        <ul class="nav navbar-nav">

          
          <li><a href="<%=root_path%>">TAREAS</a></li>
        </ul>
      </div>
    <% end %>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>September18</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%  if notice.present? %>
      <div class="alert alert-sucess" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>
<div class="container">
	<div class="row">
		<% @tasks.each_slice(3) do |row| %>
			<% row.each do |task| %>
			<div class="col">
				<div class="card" >
					<%= image_tag task.photo, :size => "200x200", class: 'card-img-top img-thumbnail' %>
					<div class="body">		
					    <h1><%= task.name %></h1>

						<p><%= task.description %></p>
						  <%= link_to "No realizada", task_assigments_path(task) , class: "btn btn-success", method: :post %>
						
					</div>
				</div>
			</div>

			<% end %>	
			<div class="w-100" style="margin:20px" ></div>
		<% end %>
	</div>
</div>